Added rotation using degrees; Redefined and extended vector constants; Minor clean-up
avdstaaij/gdpc pull request #102
Opened 2024-05-18 16:03 UTC by Flashing-Blinkenlights

I took the liberty of adding functions for rotating vectors using degrees (a little more intuitive in my opinion), and redefined a bunch of vectors allowing for greater flexibility and clarity while remaining backward-compatible.
Formatted with black, and ran a linter or two over it plus some tiny refactoring tweaks here and there.

Feel free to change anything at all, I'm up to discuss anything!

2024-05-19 22:03 UTC, avdstaaij requested changes
Some nice additions here! I did leave a bunch of comments though, please take a look at them.

Also, please revert the formatting changes. I'm generally not a fan of most automatic formatters, especially super-strict ones like black, because I find that custom formatting here and there (mainly spacing) can make code much more readable. I see many examples of that here, most notably neighbors2D and neighbors3D. Furthermore, if I'm going to standardize the code formatting, I'd rather do it all at once - doing it in a PR like this makes it harder for me to see what the actual changes are.

2024-05-19 22:08 UTC, avdstaaij commented
Looks like I forgot to submit one of my comments:

I quite like the DIAGONALS_2D/3D aliases, please move them up to the 2D/3D categories.
There is one issue though, since the original DIAGONALS constants were tuples, not sets, this is *technically* a breaking change. This may be over-careful, but please wrap them in `tuple()` and add a comment about updating them to sets on the next major version release.

2024-05-22 20:15 UTC, Flashing-Blinkenlights commented on src/gdpc/vector_tools.py
> +    return addY(rotate2Ddeg(dropY(vec), degrees), vec[1])
You can't really support any other rotations in the first place as it's an integer vector. Any non-90° rotations would result in float values. In that sense, this is internally consistent with the datatype, and is consistently documented here.

2024-05-22 20:18 UTC, Flashing-Blinkenlights commented on src/gdpc/vector_tools.py
> +IDENTITY_2D = ivec2(1, 1)
I created the identity as a stand-in for `1` as you use it in your calculations, to keep the typing consistent. If you can think of a different, more suitable name; or some other way of representing a `1` for either vector type, I'm all ears

2024-05-22 20:21 UTC, Flashing-Blinkenlights commented on src/gdpc/vector_tools.py
> +}
Basically, it's every side of the 9x9 cube that has two exposed surfaces. I can't think of a better name, but my thinking was it's the diagonals, for each orthogonal (the diagonals which lie orthogonally to each direction).

2024-05-22 20:22 UTC, Flashing-Blinkenlights commented on src/gdpc/vector_tools.py
>  )
I wanted to underline the backward compatibility as it was my hope that they might be removed in a later version to reduce ambiguity

2024-05-22 20:30 UTC, Flashing-Blinkenlights commented
> Looks like I forgot to submit one of my comments:
> 
> I quite like the DIAGONALS_2D/3D aliases, please move them up to the 2D/3D categories. There is one issue though, since the original DIAGONALS constants were tuples, not sets, this is _technically_ a breaking change. This may be over-careful, but please wrap them in `tuple()` and add a comment about updating them to sets on the next major version release.

I can't think of a use-case where a tuple would be beneficial to use over a set here. The only difference I could see is that a set is mutable, but that's still reverse-compatible
On the other hand, having these vectors as sets allows for operations such as unions and intersects with other sets of vectors, which would not be possible with a tuple, hence I think converting them is unnecessary and may prevent the use of its full functionality.

2024-05-22 20:39 UTC, Flashing-Blinkenlights commented
> Some nice additions here! I did leave a bunch of comments though, please take a look at them.
> 
> Please revert the formatting changes, though. I'm generally not a fan of most automatic formatters, especially super-strict ones like black, because I find that custom formatting here and there (mainly spacing) can make code much more readable. I see many examples of that here, most notably neighbors2D and neighbors3D. Furthermore, if I'm going to standardize the code formatting, I'd rather do it all at once - doing it in a PR like this makes it harder for me to see what the actual changes are.

Should I revert *all* non-functional changes, including isort, newlines, spacing between operators, commas at the end of listings and type annotations?

2024-05-23 14:59 UTC, avdstaaij commented
(Discussion continued on Discord)

2024-05-24 11:51 UTC, Flashing-Blinkenlights commented on src/gdpc/vector_tools.py
> +}
For now, will keep this name

2024-05-25 20:59 UTC, avdstaaij requested changes
I've got a few more comments, mostly formatting nitpicks but a few functional comments as well.

I've ignored most formatting changes, but I did comment on the ones that I found actively detrimental. I'll look into putting up an autoformatter soon! Maybe I need to let go of custom formatting for the sake of consistency... but I'm not quite ready yet. I _do_ want any color I like sometimes.

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +DIRECTIONS, DIRECTIONS_AND_EDGE_DIAGONALS, DIRECTIONS_AND_ALL_DIAGONALS = DIRECTIONS_3D, DIRECTIONS_AND_EDGE_DIAGONALS_3D, DIRECTIONS_AND_ALL_DIAGONALS_3D
Please remove the comment and put each alias on a new line.

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +    if rotation == 3: return ivec2(vec[1], -vec[0])
Please revert the spacing changes. I'll put up an autoformatter issue soon(tm)!

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +def directionToRotation(direction: Vec2iLike) -> Literal[0] | Literal[1] | Literal[2] | Literal[3]:
Use `Union` instead of `|` so we keep Python 3.7 compatibility. I know it's ugly... maybe I'll increase the required version at some point, but I'd like to keep it until at least the next major release.

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +    if len(vec) == 3: return int(glm.length2(*vec3(*vec)))
Why are there unpacking operators here? This throws a TypeError on my machine.

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +def orderedCorners2D(corner1: Vec2iLike, corner2: Vec2iLike) -> tuple[ivec2, ivec2]:
Use `Tuple` instead of `tuple` for Python 3.7 compatibility.

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +def orderedCorners3D(corner1: Vec3iLike, corner2: Vec3iLike) -> tuple[ivec3, ivec3]:
`Tuple`

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +            and self.end.y >= other.begin.y
Please revert whitespace changes. Putting `and` at the start is ok, but then align the first item with extra spaces.

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +        yield from loop2D(ivec2(first.x, last.y), ivec2(first.x, first.y + 1) - 1)
Please revert whitespace changes.

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +            and self.begin.z <= vec[2] < self.end.z
See earlier comment.

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +            and self.end.z >= other.begin.z
See earlier comment.

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +    array[box.begin.x : box.end.x, box.begin.y : box.end.y, box.begin.z : box.end.z] = (value)
Why are there parentheses around `value`?

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +    if end is None: begin, end = (0, 0, 0), begin
Please revert.

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +    if not includeInputPoints: filled -= pointMap
Some changes here I like, some I don't. Please revert for now. Style issue coming... maybe tomorrow?

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +    if not includeInputPoints: filled -= pointMap
Please revert for now.

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +    end = np.array(end)
Why did you remove these type hints?

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +    ] / maxDelta + np.array(begin)
Please revert.

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
>      If <diameter>[axis] is even, <center>[axis] will be the lower center point in that axis."""
That `\n` was there for a reason!

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +    # NOTE: This is very memory-inefficient. Consider combining conditions into trees, or iterating through a set of vector constants.
Please remove this comment. I don't quite understand what you mean here, so this comment is not very useful to me. If you have a better implementation, feel free to PR it in though!

2024-05-25 20:59 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +        rotation += 4  # Invert negative turns
This is not necessary since Python's % operator is actually true modulo.

2024-05-25 21:17 UTC, Flashing-Blinkenlights commented on src/gdpc/vector_tools.py
> +    end = np.array(end)
`begin` and `end` are already defined as parameters
If we'd like to use these type hints, then we should rename the new variables to e.g. `_begin` and `_end` to prevent the type annotation from conflicting

2024-05-25 21:18 UTC, Flashing-Blinkenlights commented on src/gdpc/vector_tools.py
>      If <diameter>[axis] is even, <center>[axis] will be the lower center point in that axis."""
Purely out of interest, what reason?

2024-05-25 21:19 UTC, Flashing-Blinkenlights commented on src/gdpc/vector_tools.py
> +        rotation += 4  # Invert negative turns
The more you know!

2024-05-25 21:23 UTC, Flashing-Blinkenlights commented on src/gdpc/vector_tools.py
> +    if len(vec) == 3: return int(glm.length2(*vec3(*vec)))
On my other device there wasn't a suitable override for the vec2/vec3 in `glm.length2()`, but there was one for separate x, y and z values.
I've reverted the change, as you're probably right.

2024-05-25 21:26 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +    end = np.array(end)
Ah, that makes sense. I'm fine with either option (no type hint / new names).

2024-05-25 21:29 UTC, avdstaaij commented on src/gdpc/vector_tools.py
>      If <diameter>[axis] is even, <center>[axis] will be the lower center point in that axis."""
It's a newline to split the first line of the docstring (which is treated differently in most cases) from the second. The proper way to write docstrings is to put an actual empty line there, but I abbreviated it in a lot of places with "\n". This may go away if we add an autoformatter, but there should at least be a `\n` _or_ an actual empty line there.

2024-05-25 21:33 UTC, Flashing-Blinkenlights commented on src/gdpc/vector_tools.py
>      If <diameter>[axis] is even, <center>[axis] will be the lower center point in that axis."""
Ah I see, I personally would have put a new line between the two then

2024-05-25 21:46 UTC, Flashing-Blinkenlights commented on src/gdpc/vector_tools.py
> +    array[box.begin.x : box.end.x, box.begin.y : box.end.y, box.begin.z : box.end.z] = (value)
An artifact from me not properly reverting the formatting

2024-05-25 21:52 UTC, avdstaaij approved these changes

2024-05-25 21:52 UTC, merged