Made constants immutable; added ordered vector constants; added generators for vector constants; simplified neighbour functions
avdstaaij/gdpc pull request #103
Opened 2024-05-27 19:54 UTC by Flashing-Blinkenlights

Sorry for making another PR, but I just couldn't help myself!

2024-05-27 23:24 UTC, avdstaaij requested changes
The refactored neighbors functions look good! I see now what you meant with your previous comment. I do have a bunch of comments again, though.

Also, a general comment: prefer to not type hint local variables when the type can be inferred (e.g. `x: int = 1`). It's not really needed, and it can reduce readability for complex types. Most modern statically typed languages don't explicitly state types in these cases either (e.g. in C++, you'd use `auto x = 1`).

2024-05-27 23:24 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +            yield candidate
See comments 1 and 2 for rotate_ordered_vectors_2D.

The `vectors` typehint here could simply be `Iterable[ivec2]`. In general, prefer `Iterable` over `Sequence` if you only iterate through the collection.

Furthermore, this name is not very clear to me. "inbound" usually means "approaching". Could you try to come up with a clearer name?

2024-05-27 23:24 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +            yield candidate
See previous comment.

2024-05-27 23:24 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +
I suppose this is consistent with EDGE_DIAGONALS and CORNER_DIAGONALS, but those names should be the exception rather than the rule. A better name for this would be ZERO_2D or ORIGIN_2D, but really, I don't think this is needed. You can just use `0` in most cases.

2024-05-27 23:24 UTC, avdstaaij commented on src/gdpc/vector_tools.py
> +CENTER_3D = ivec3(0, 0, 0)
See previous comment.

2024-05-28 06:11 UTC, Flashing-Blinkenlights commented on src/gdpc/vector_tools.py
> +ORDERED_COUNTER_CARDINALS_AND_DIAGONALS_2D: Tuple[ivec2, ...] = tuple(itertools.chain.from_iterable(zip(ORDERED_COUNTER_CARDINALS_2D, ORDERED_COUNTER_INTERCARDINALS_2D)))
Oh yes, I forgot to take them out

2024-05-28 06:32 UTC, Flashing-Blinkenlights commented on src/gdpc/vector_tools.py
> +            yield candidate
With "inbound" I mean "within the bounds of the bounding box", as that's really what `neighbors` is doing: Returning each neighbor which is " in bounds"

2024-05-28 06:34 UTC, Flashing-Blinkenlights commented on src/gdpc/vector_tools.py
I merged post-changes, and must've used the merger incorrectly

2024-05-28 22:13 UTC, avdstaaij approved these changes
Looks good! Good catches in utils.py as well. I may do a few more tweaks, but they'll be to the private functions so it won't affect the interface. You did remove a bunch of newlines in the spots where you had duplicated the function signatures before, but I'll fix that as well.

2024-05-28 22:14 UTC, merged