Add compatibility with Minecraft 1.19.2 / gdmc_http_interface 0.5.0
avdstaaij/gdpc pull request #51
Opened 2022-12-06 22:56 UTC by Niels-NTG

Solves for #46 

Most of it stays unchanged except for changes to get the new data structure for world chunks working.

There's still an open ToDo to update `lookup.py` with new blocks that have been added since after the release of Minecraft 1.16.5. But that is non-essential and is mostly for the benefit of `visualizeMap.py` at present. This can be done in a separate PR.

2022-12-07 17:31 UTC, Niels-NTG commented
Also solves #41 , since I used `visualizeMap.py` as one of the way to test the new world chunk data structure.

2022-12-08 19:55 UTC, avdstaaij requested changes
Please re-target this to the `dev` branch.

2022-12-08 19:55 UTC, avdstaaij commented on Start_Here.py
> +    # >>> input("Waiting for user to press [Enter]")
Why did you add comment signs here? Would that not give readers the impression that the described lines should be comments?

2022-12-08 19:55 UTC, avdstaaij commented on gdpc/worldLoader.py
> +                break
If I understand correctly, chunks are now stored as a flat list instead of a 3D array, which means that the whole list needs to be searched to find a chunk. This seems inefficient. Is the 3D array no longer possible? If not, you could perhaps use a dict to map chunk coordinates to the chunk.

This can be merged regardless, though. Getting it to work at all is more important.

2022-12-08 19:55 UTC, avdstaaij commented on requirements.txt
> +numpy==1.23.5
Are these updates required? If not, I'd keep them as they were for better compatibility.

2022-12-09 10:43 UTC, Niels-NTG commented on requirements.txt
> +numpy==1.23.5
Updating the NBT library to 1.5.1 did help make this project a bit easier since it added better support for more recent Minecraft versions, as well as having support for Python 3.10, which is nice to have. Updating matplotlib cannot hurt. But I do admit that updating numpy *just cause* may have unforeseen consequences. I will roll that one back.

2022-12-09 10:56 UTC, Niels-NTG commented on Start_Here.py
> +    # >>> input("Waiting for user to press [Enter]")
I shouldn't have committed this. I reverted it.

2022-12-09 11:02 UTC, Niels-NTG commented on gdpc/worldLoader.py
> +                break
The 3D array is no longer possible if the chunk indices can use negative integer values for the Y value. So me with my JavaScript brain came up with this admittedly inefficient solution. I wasn't aware that keys in a dict can be any data type, not just strings. So I've now implemented `self.sections` as a dict that uses `(x, y, z)` as keys.

2022-12-11 21:20 UTC, avdstaaij commented on requirements.txt
> +numpy==1.23.5
Sounds sensible!

2022-12-11 21:26 UTC, avdstaaij approved these changes
Looks good now!

I've confirmed that the examples run with this change and GDMC-HTTP 0.5.0.

It's unfortunate that this does break compatibility with Minecraft 1.16.5. We should probably implement a system in GDPC to switch between underlying interface implementations, but that can be done in a future version.

2022-12-11 21:27 UTC, merged