Added sphere to geometery and vector_tools
avdstaaij/gdpc pull request #76
Opened 2023-03-18 20:04 UTC by cmoyates

2023-03-19 03:19 UTC, avdstaaij requested changes
Thank you for the contribution!

Unfortunately, there are quite a few small issues that need to be fixed before this can be merged. I've explained them in as much detail as possible to help you avoid them in any future PRs.

2023-03-19 03:19 UTC, avdstaaij commented on gdpc/vector_tools.py
> +def ellipsoid(center: Vec3iLike, radii: Vec3iLike, hollow: bool = False, wall_thickness: int = 1) -> list[Vec3iLike]:
A couple of notes about the type hint here:
1. Using `list` as type hint requires a fairly new version of Python. For compatibility, this should be `List` (with a capital L, from the `typing` module). I could unfortunately not test the code due to this.
2. This may be an uncommon opinion, but I actually prefer to not add type hints to functions at all. The reason is that they "shadow" the type that the function actually returns: you could write `return 1` and the function would still report that it always returns `List[Vec3iLike]`. My editor can deduce the actual return type of the function from its implementation, which is much less error-prone. Of course, a static type-checker that enforces type correctness would be even more robust, but GDPC has some objects that don't mesh well with them (like `Vec3iLike`).
3. As proof of point 2, this function does not actually return `Vec3iLike`s. `Vec3iLike` is an *abstract base class*: it indicates a type that *behaves* like a 3D vector. It's not something you can actually instantiate. (Yes, I may have over-engineered this...) What this function actually returns, is a `List[Tuple[int,int,int]]`. Furthermore, it should actually return `ivec3` objects instead of tuples for consistency with the other point generating functions. 
4. *Actually*, This function should not even return a list - it should *yield* points. See my comment further below.

2023-03-19 03:19 UTC, avdstaaij commented on gdpc/vector_tools.py
> +    points = []
For consistency with the other geometry point generating functions (and for better performance in some cases), this function should be a *generator*: it should `yield` the points it computes instead of storing them in an intermediary list. You can take a look at the other functions here to see how it works.

2023-03-19 03:19 UTC, avdstaaij commented on gdpc/vector_tools.py
> +            for z in range(z0 - c, z0 + c + 1):
You could also do this with `loop3D` - but this works as well.

2023-03-19 03:19 UTC, avdstaaij commented on gdpc/vector_tools.py
> +                            points.append((x, y, z))
To summarize some of my earlier comments, this should be:
`yield ivec3(x,y,z)`

2023-03-19 04:08 UTC, cmoyates commented on gdpc/vector_tools.py
> +            for z in range(z0 - c, z0 + c + 1):
I would assume that this is basically what's going on under the hood there, so I've left this as is.

2023-03-19 15:01 UTC, avdstaaij requested changes
Excellent, almost there!

I've tested the code and it works as expected. The "midpoint" ellipses are different in shape than those generated by `ellipse`, but honestly, I think they look better. So I wouldn't change anything there.

One last note: please change the radius/radii parameters to diameter parameters, like the `ellipse` and `cylinder` functions. There are two reasons for using diameters instead of radii:
- They are unambiguous. With radii there is always the question of whether or not the origin point is counted.
- They allow you to specify even-width ellipsoids.

For even-width ellipsoids, the behavior should be just like `ellipse()`: `center` should be the "lower" center point. For example, if `center` is (0,0,0) and the diameter is even in each axis, the eight center points should be (0,0,0) -- (1,1,1).

2023-03-20 19:34 UTC, avdstaaij approved these changes
Needs a few comment/docstring changes, but I'll do those myself.

2023-03-20 19:34 UTC, merged