Place and get structure endpoint
avdstaaij/gdpc pull request #81
Opened 2023-03-21 22:35 UTC by Niels-NTG

Implements interfaces for the [`POST /structure`](https://github.com/Niels-NTG/gdmc_http_interface/blob/master/docs/Endpoints.md#place-nbt-structure-file-post-structure) and [`GET /structure`](https://github.com/Niels-NTG/gdmc_http_interface/blob/master/docs/Endpoints.md#create-nbt-structure-file-get-structure) endpoints present in GDMC-HTTP.

This doesn't currently include any integration with the `Editor` class or an util method that help with loading and saving `*.nbt` files. I would want to include these as well but don't know where best to put these.

2023-03-28 16:08 UTC, avdstaaij requested changes
The `interface.py` wrappers look good. I do however have a bunch of comments, mostly about the docstrings. In particular, I think we should be precise about the difference between a "file" and "the contents of a file", and the difference between "an nbt file" and "a structure file" (this is especially important because _schematic_ files are also nbt files).

There should also be a higher-level interface for structure files in the `Editor` class, making use of its transform. But that can also be added after this PR.

About the `nbt_tools.py` additions: I am generally against adding functions that are not used anywhere, but some of these are indeed quite useful.

2023-03-28 16:21 UTC, avdstaaij commented
By the way, a question: do structures in the GDMC-HTTP mod have a maximum size like they do in-game? (48x48x48 in Java edition according to the wiki.) If so, what happens when you request a structure larger than that?

2023-03-28 18:39 UTC, Niels-NTG commented
> By the way, a question: do structures in the GDMC-HTTP mod have a maximum size like they do in-game? (48x48x48 in Java edition according to the wiki.) If so, what happens when you request a structure larger than that?

During the development of the `POST /structure` and `GET /structure` endpoint I didn't encounter any of those limits. I managed to "copy-paste" entire villages including all inhabitants, much larger than 48x48x48 blocks, without issue. As far as I know the 48x48x48 limit only applies to structures that can be saved using the in-game [Structure Block](https://minecraft.fandom.com/wiki/Structure_Block). This limitation can be overcome by creating structure files via other methods, such as the `GET /structure` endpoint or mods like WorldEdit.

2023-03-28 20:46 UTC, avdstaaij commented
That's good news!

2023-03-29 22:24 UTC, avdstaaij requested changes

2023-03-29 22:24 UTC, avdstaaij commented on gdpc/interface.py
> +        mirrorArg = 'z'
This looks like it does not support simultaneous x and z mirroring. Does GDMC-HTTP support simultaneous mirroring? If not, it should be emulated here by converting it to the equivalent rotation.

2023-03-29 22:24 UTC, avdstaaij commented on gdpc/nbt_tools.py
> +def saveNbtTFile(
I think you missed a letter here ;)

2023-03-30 21:49 UTC, avdstaaij requested changes

2023-03-30 21:49 UTC, avdstaaij commented on gdpc/interface.py
> +        rotate = 1
I believe this is still not correct: mirroring in one axis changes the structure's "orientation", while mirroring in two axes does not. This currently also overwrites the original `rotate` value. I'm pretty sure this should be:
```python
if mirror[0] and mirror[1]:
    rotate = (rotate + 2) % 4
```

2023-03-30 21:52 UTC, avdstaaij commented
One more question: in what order does the GDMC-HTTP endpoint do mirroring and rotating? Mirror -> rotate or rotate -> mirror? (These are not equivalent!)
Every system in GDPC that has rotation and mirroring does mirroring first and rotation second, so if GDMC-HTTP works the other way around, we need to do some thinking to correct for that here.

2023-03-31 07:26 UTC, Niels-NTG commented
> One more question: in what order does the GDMC-HTTP endpoint do mirroring and rotating? Mirror -> rotate or rotate -> mirror? (These are not equivalent!) Every system in GDPC that has rotation and mirroring does mirroring first and rotation second, so if GDMC-HTTP works the other way around, we need to do some thinking to correct for that here.

Looking at the `transform` method in `StructureTemplate.java` reveals that it first applies the mirror, than the rotation.

2023-03-31 07:27 UTC, Niels-NTG commented on gdpc/interface.py
> +        rotate = 1
:facepalm: yes, of course…

2023-03-31 21:27 UTC, avdstaaij approved these changes

2023-03-31 21:27 UTC, merged